# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from sse_interface.v1 import sse_pb2 as sse__interface_dot_v1_dot_sse__pb2


class SSEServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TranspileAndExec = channel.unary_unary(
                '/sse_interface.v1.SSEService/TranspileAndExec',
                request_serializer=sse__interface_dot_v1_dot_sse__pb2.TranspileAndExecRequest.SerializeToString,
                response_deserializer=sse__interface_dot_v1_dot_sse__pb2.TranspileAndExecResponse.FromString,
                )


class SSEServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TranspileAndExec(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SSEServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TranspileAndExec': grpc.unary_unary_rpc_method_handler(
                    servicer.TranspileAndExec,
                    request_deserializer=sse__interface_dot_v1_dot_sse__pb2.TranspileAndExecRequest.FromString,
                    response_serializer=sse__interface_dot_v1_dot_sse__pb2.TranspileAndExecResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sse_interface.v1.SSEService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SSEService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TranspileAndExec(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sse_interface.v1.SSEService/TranspileAndExec',
            sse__interface_dot_v1_dot_sse__pb2.TranspileAndExecRequest.SerializeToString,
            sse__interface_dot_v1_dot_sse__pb2.TranspileAndExecResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
