# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sse_interface/v1/sse.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1asse_interface/v1/sse.proto\x12\x10sse_interface.v1\"=\n\x17TranspileAndExecRequest\x12\"\n\rjob_data_json\x18\x01 \x01(\tR\x0bjobDataJson\"\xb6\x01\n\x18TranspileAndExecResponse\x12\x16\n\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n\x07message\x18\x02 \x01(\tR\x07message\x12\'\n\x0ftranspiler_info\x18\x03 \x01(\tR\x0etranspilerInfo\x12\'\n\x0ftranspiled_qasm\x18\x04 \x01(\tR\x0etranspiledQasm\x12\x16\n\x06result\x18\x05 \x01(\tR\x06result2w\n\nSSEService\x12i\n\x10TranspileAndExec\x12).sse_interface.v1.TranspileAndExecRequest\x1a*.sse_interface.v1.TranspileAndExecResponseB\xa3\x01\n\x14\x63om.sse_interface.v1B\x08SseProtoP\x01Z$sse/sse_interface/v1;sse_interfacev1\xa2\x02\x03SXX\xaa\x02\x0fSseInterface.V1\xca\x02\x0fSseInterface\\V1\xe2\x02\x1bSseInterface\\V1\\GPBMetadata\xea\x02\x10SseInterface::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sse_interface.v1.sse_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024com.sse_interface.v1B\010SseProtoP\001Z$sse/sse_interface/v1;sse_interfacev1\242\002\003SXX\252\002\017SseInterface.V1\312\002\017SseInterface\\V1\342\002\033SseInterface\\V1\\GPBMetadata\352\002\020SseInterface::V1'
  _globals['_TRANSPILEANDEXECREQUEST']._serialized_start=48
  _globals['_TRANSPILEANDEXECREQUEST']._serialized_end=109
  _globals['_TRANSPILEANDEXECRESPONSE']._serialized_start=112
  _globals['_TRANSPILEANDEXECRESPONSE']._serialized_end=294
  _globals['_SSESERVICE']._serialized_start=296
  _globals['_SSESERVICE']._serialized_end=415
# @@protoc_insertion_point(module_scope)
