[project]
name = "estimation"
version = "1.0.0"
dependencies = [
    "grpcio==1.66.1",
    "numpy==2.1.3",
    "protobuf==5.29.5",
    "pydantic==2.10.2",
    "pytest==8.3.3",
    "qiskit==1.4.2",
    "qiskit-aer==0.15.1",
    "qiskit-qasm3-import==0.5.0",
]

[tool.uv]
package = false
