[project]
name = "estimation"
version = "1.0.0"
dependencies = [
  "grpcio==1.66.1",
  "numpy==2.1.3",
  "protobuf==6.31.1",
  "pydantic==2.10.2",
  "pytest==8.3.3",
  "qiskit==1.2.4",
  "qiskit-aer==0.15.1",
  "qiskit-qasm3-import==0.5.0",
]

[tool.uv]
package = false
