# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: multiprog_interface/v1/multiprog.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&multiprog_interface/v1/multiprog.proto\x12\x16multiprog_interface.v1\"N\n\x0e\x43ombineRequest\x12\x1d\n\nqasm_array\x18\x01 \x01(\tR\tqasmArray\x12\x1d\n\nmax_qubits\x18\x02 \x01(\x05R\tmaxQubits\"\xb1\x01\n\x0f\x43ombineResponse\x12G\n\x0f\x63ombined_status\x18\x01 \x01(\x0e\x32\x1e.multiprog_interface.v1.StatusR\x0e\x63ombinedStatus\x12#\n\rcombined_qasm\x18\x02 \x01(\tR\x0c\x63ombinedQasm\x12\x30\n\x14\x63ombined_qubits_list\x18\x03 \x03(\x05R\x12\x63ombinedQubitsList*O\n\x06Status\x12\x12\n\x0eSTATUS_SUCCESS\x10\x00\x12\x12\n\x0eSTATUS_FAILURE\x10\x01\x12\x1d\n\x19STATUS_INVALID_QUBIT_SIZE\x10\x02\x32t\n\x16\x43ircuitCombinerService\x12Z\n\x07\x43ombine\x12&.multiprog_interface.v1.CombineRequest\x1a\'.multiprog_interface.v1.CombineResponseB\xe0\x01\n\x1a\x63om.multiprog_interface.v1B\x0eMultiprogProtoP\x01Z=multiprog/manual/multiprog_interface/v1;multiprog_interfacev1\xa2\x02\x03MXX\xaa\x02\x15MultiprogInterface.V1\xca\x02\x15MultiprogInterface\\V1\xe2\x02!MultiprogInterface\\V1\\GPBMetadata\xea\x02\x16MultiprogInterface::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'multiprog_interface.v1.multiprog_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\032com.multiprog_interface.v1B\016MultiprogProtoP\001Z=multiprog/manual/multiprog_interface/v1;multiprog_interfacev1\242\002\003MXX\252\002\025MultiprogInterface.V1\312\002\025MultiprogInterface\\V1\342\002!MultiprogInterface\\V1\\GPBMetadata\352\002\026MultiprogInterface::V1'
  _globals['_STATUS']._serialized_start=326
  _globals['_STATUS']._serialized_end=405
  _globals['_COMBINEREQUEST']._serialized_start=66
  _globals['_COMBINEREQUEST']._serialized_end=144
  _globals['_COMBINERESPONSE']._serialized_start=147
  _globals['_COMBINERESPONSE']._serialized_end=324
  _globals['_CIRCUITCOMBINERSERVICE']._serialized_start=407
  _globals['_CIRCUITCOMBINERSERVICE']._serialized_end=523
# @@protoc_insertion_point(module_scope)
