[project]
name = "mitigation"
version = "1.0.0"
dependencies = [
    "grpcio==1.68.1",
    "numpy==2.2.2",
    "protobuf==5.29.3",
    "pydantic==2.10.6",
    "pytest==8.3.3",
    "qiskit==1.3.0",
]

[tool.uv]
package = false
