# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from mitigation_interface.v1 import (
    mitigation_pb2 as mitigation__interface_dot_v1_dot_mitigation__pb2,
)


class ErrorMitigatorServiceStub(object):
    """RPC service for Error Mitigation"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReqMitigation = channel.unary_unary(
            "/mitigation_interface.v1.ErrorMitigatorService/ReqMitigation",
            request_serializer=mitigation__interface_dot_v1_dot_mitigation__pb2.ReqMitigationRequest.SerializeToString,
            response_deserializer=mitigation__interface_dot_v1_dot_mitigation__pb2.ReqMitigationResponse.FromString,
            _registered_method=True,
        )


class ErrorMitigatorServiceServicer(object):
    """RPC service for Error Mitigation"""

    def ReqMitigation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ErrorMitigatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ReqMitigation": grpc.unary_unary_rpc_method_handler(
            servicer.ReqMitigation,
            request_deserializer=mitigation__interface_dot_v1_dot_mitigation__pb2.ReqMitigationRequest.FromString,
            response_serializer=mitigation__interface_dot_v1_dot_mitigation__pb2.ReqMitigationResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "mitigation_interface.v1.ErrorMitigatorService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "mitigation_interface.v1.ErrorMitigatorService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class ErrorMitigatorService(object):
    """RPC service for Error Mitigation"""

    @staticmethod
    def ReqMitigation(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mitigation_interface.v1.ErrorMitigatorService/ReqMitigation",
            mitigation__interface_dot_v1_dot_mitigation__pb2.ReqMitigationRequest.SerializeToString,
            mitigation__interface_dot_v1_dot_mitigation__pb2.ReqMitigationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
