# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mitigation_interface/v1/mitigation.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(mitigation_interface/v1/mitigation.proto\x12\x17mitigation_interface.v1\"2\n\x08MesError\x12\x12\n\x04p0m1\x18\x01 \x01(\x02R\x04p0m1\x12\x12\n\x04p1m0\x18\x02 \x01(\x02R\x04p1m0\"\x96\x01\n\x05Qubit\x12\x0e\n\x02id\x18\x01 \x01(\x05R\x02id\x12\x0e\n\x02t1\x18\x02 \x01(\x02R\x02t1\x12\x0e\n\x02t2\x18\x03 \x01(\x02R\x02t2\x12\x1d\n\ngate_error\x18\x04 \x01(\x02R\tgateError\x12>\n\tmes_error\x18\x05 \x01(\x0b\x32!.mitigation_interface.v1.MesErrorR\x08mesError\"\\\n\x0e\x44\x65viceTopology\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12\x36\n\x06qubits\x18\x02 \x03(\x0b\x32\x1e.mitigation_interface.v1.QubitR\x06qubits\"\x90\x02\n\x14ReqMitigationRequest\x12P\n\x0f\x64\x65vice_topology\x18\x01 \x01(\x0b\x32\'.mitigation_interface.v1.DeviceTopologyR\x0e\x64\x65viceTopology\x12Q\n\x06\x63ounts\x18\x02 \x03(\x0b\x32\x39.mitigation_interface.v1.ReqMitigationRequest.CountsEntryR\x06\x63ounts\x12\x18\n\x07program\x18\x03 \x01(\tR\x07program\x1a\x39\n\x0b\x43ountsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\x05R\x05value:\x02\x38\x01\"\xa6\x01\n\x15ReqMitigationResponse\x12R\n\x06\x63ounts\x18\x01 \x03(\x0b\x32:.mitigation_interface.v1.ReqMitigationResponse.CountsEntryR\x06\x63ounts\x1a\x39\n\x0b\x43ountsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\x05R\x05value:\x02\x38\x01\x32\x87\x01\n\x15\x45rrorMitigatorService\x12n\n\rReqMitigation\x12-.mitigation_interface.v1.ReqMitigationRequest\x1a..mitigation_interface.v1.ReqMitigationResponseB\xdd\x01\n\x1b\x63om.mitigation_interface.v1B\x0fMitigationProtoP\x01Z4mitig/mitigation_interface/v1;mitigation_interfacev1\xa2\x02\x03MXX\xaa\x02\x16MitigationInterface.V1\xca\x02\x16MitigationInterface\\V1\xe2\x02\"MitigationInterface\\V1\\GPBMetadata\xea\x02\x17MitigationInterface::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mitigation_interface.v1.mitigation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.mitigation_interface.v1B\017MitigationProtoP\001Z4mitig/mitigation_interface/v1;mitigation_interfacev1\242\002\003MXX\252\002\026MitigationInterface.V1\312\002\026MitigationInterface\\V1\342\002\"MitigationInterface\\V1\\GPBMetadata\352\002\027MitigationInterface::V1'
  _globals['_REQMITIGATIONREQUEST_COUNTSENTRY']._loaded_options = None
  _globals['_REQMITIGATIONREQUEST_COUNTSENTRY']._serialized_options = b'8\001'
  _globals['_REQMITIGATIONRESPONSE_COUNTSENTRY']._loaded_options = None
  _globals['_REQMITIGATIONRESPONSE_COUNTSENTRY']._serialized_options = b'8\001'
  _globals['_MESERROR']._serialized_start=69
  _globals['_MESERROR']._serialized_end=119
  _globals['_QUBIT']._serialized_start=122
  _globals['_QUBIT']._serialized_end=272
  _globals['_DEVICETOPOLOGY']._serialized_start=274
  _globals['_DEVICETOPOLOGY']._serialized_end=366
  _globals['_REQMITIGATIONREQUEST']._serialized_start=369
  _globals['_REQMITIGATIONREQUEST']._serialized_end=641
  _globals['_REQMITIGATIONREQUEST_COUNTSENTRY']._serialized_start=584
  _globals['_REQMITIGATIONREQUEST_COUNTSENTRY']._serialized_end=641
  _globals['_REQMITIGATIONRESPONSE']._serialized_start=644
  _globals['_REQMITIGATIONRESPONSE']._serialized_end=810
  _globals['_REQMITIGATIONRESPONSE_COUNTSENTRY']._serialized_start=584
  _globals['_REQMITIGATIONRESPONSE_COUNTSENTRY']._serialized_end=641
  _globals['_ERRORMITIGATORSERVICE']._serialized_start=813
  _globals['_ERRORMITIGATORSERVICE']._serialized_end=948
# @@protoc_insertion_point(module_scope)
